# Generated by Django 5.0.4 on 2024-05-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_assigndetails_status_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead_time',
            field=models.DateTimeField(default=''),
        ),
    ]
