# Generated by Django 5.0.4 on 2024-05-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_id_post_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uuid',
            new_name='id',
        ),
    ]
