# Generated by Django 5.0.4 on 2024-05-06 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='authorization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_authorizatoin', to='core.authorization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ASSOCIATE_TRAINEE', 'Associate trainee'), ('TECHNICAL_TRAINER', 'Technical trainer'), ('MANAGER', 'Manager')], default='ASSOCIATE_TRAINEE', max_length=40),
        ),
    ]
